"""create_all_tables

Revision ID: 76e194a9b7ba
Revises:
Create Date: 2026-09-16 19:14:25.654440+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '76e194a9b7ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='api', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('publish_mode', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    op.create_index(op.f('ix_sites_slug'), 'sites', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('scopes', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('uses_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_actors_site_id_sites'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
    )
    op.create_table('redirects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('old_slug', sa.String(length=256), nullable=False),
    sa.Column('new_slug', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), server_default='301', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_redirects_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redirects')),
    sa.UniqueConstraint('site_id', 'old_slug', name='uq_redirects_site_id_old_slug')
    )
    op.create_index(op.f('ix_redirects_site_id'), 'redirects', ['site_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=True),
    sa.Column('events', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_webhooks_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks'))
    )
    op.create_index(op.f('ix_webhooks_site_id'), 'webhooks', ['site_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('created_by_actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actors.id'], name=op.f('fk_assets_created_by_actor_id_actors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_assets_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_table('capability_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('path_scope', sa.String(length=512), server_default='/', nullable=False),
    sa.Column('verbs', sa.JSON(), server_default='["GET"]', nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uses_remaining', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_capability_links_actor_id_actors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_links'))
    )
    op.create_index(op.f('ix_capability_links_actor_id'), 'capability_links', ['actor_id'], unique=False)
    op.create_index(op.f('ix_capability_links_token_hash'), 'capability_links', ['token_hash'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), server_default='', nullable=False),
    sa.Column('body_md', sa.Text(), server_default='', nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('frontmatter', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('author_label', sa.String(length=256), nullable=True),
    sa.Column('created_by_actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('unpublish_at', sa.DateTime(), nullable=True),
    sa.Column('revision_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actors.id'], name=op.f('fk_posts_created_by_actor_id_actors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_posts_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('site_id', 'slug', name='uq_posts_site_id_slug')
    )
    op.create_index(op.f('ix_posts_site_id'), 'posts', ['site_id'], unique=False)
    op.create_index('ix_posts_site_status_pub_id', 'posts', ['site_id', 'status', sa.literal_column('published_at DESC'), 'id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('fk_webhook_deliveries_webhook_id_webhooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('post_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), server_default='', nullable=False),
    sa.Column('body_md', sa.Text(), server_default='', nullable=False),
    sa.Column('frontmatter', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('editor_label', sa.String(length=256), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('diff_unified', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_post_revisions_actor_id_actors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_revisions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_revisions'))
    )
    op.create_index(op.f('ix_post_revisions_post_id'), 'post_revisions', ['post_id'], unique=False)
    op.create_table('post_tags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_tags_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name=op.f('pk_post_tags')),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tags_post_id_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_post_revisions_post_id'), table_name='post_revisions')
    op.drop_table('post_revisions')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index('ix_posts_site_status_pub_id', table_name='posts')
    op.drop_index(op.f('ix_posts_site_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_capability_links_token_hash'), table_name='capability_links')
    op.drop_index(op.f('ix_capability_links_actor_id'), table_name='capability_links')
    op.drop_table('capability_links')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_webhooks_site_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_redirects_site_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_table('actors')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sites_slug'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
