#!/usr/bin/env bash
# bootstrap_vm.sh — One-command VM bootstrap for AgentCMS (#31).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/your-org/agentcms/main/scripts/bootstrap_vm.sh | bash -s -- --domain cms.example.com --email admin@example.com
#
# Or download and run manually:
#   wget https://raw.githubusercontent.com/your-org/agentcms/main/scripts/bootstrap_vm.sh
#   chmod +x bootstrap_vm.sh
#   ./bootstrap_vm.sh --domain cms.example.com --email admin@example.com

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[BOOTSTRAP]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[BOOTSTRAP]${NC} $*"; }
log_error() { echo -e "${RED}[BOOTSTRAP]${NC} $*"; }

# Defaults
DOMAIN=""
EMAIL=""
REPO_URL="https://github.com/your-org/agentcms.git"
INSTALL_DIR="/opt/agentcms"
BRANCH="main"

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --repo)
            REPO_URL="$2"
            shift 2
            ;;
        --dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --branch)
            BRANCH="$2"
            shift 2
            ;;
        *)
            log_error "Unknown argument: $1"
            echo "Usage: $0 --domain DOMAIN --email EMAIL [--repo REPO_URL] [--dir INSTALL_DIR] [--branch BRANCH]"
            exit 1
            ;;
    esac
done

if [[ -z "$DOMAIN" || -z "$EMAIL" ]]; then
    log_error "Both --domain and --email are required"
    echo "Usage: $0 --domain DOMAIN --email EMAIL [--repo REPO_URL] [--dir INSTALL_DIR] [--branch BRANCH]"
    exit 1
fi

log_info "Bootstrapping AgentCMS on VM for domain: $DOMAIN"

# 1. Install Docker & Compose v2
log_info "Installing Docker & Compose v2..."
apt-get update
apt-get install -y ca-certificates curl gnupg lsb-release git python3 openssl

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Verify
docker compose version

# 2. Clone repo
log_info "Cloning repository to $INSTALL_DIR..."
if [[ -d "$INSTALL_DIR" ]]; then
    log_warn "$INSTALL_DIR already exists, pulling latest..."
    cd "$INSTALL_DIR"
    git fetch origin
    git checkout "$BRANCH"
    git pull origin "$BRANCH"
else
    git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# 3. Generate secrets and create .env
log_info "Generating secrets and configuring .env..."

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
POSTGRES_PASSWORD=$(openssl rand -hex 24)  # hex: it is interpolated into DATABASE_URL
METRICS_TOKEN=$(openssl rand -base64 32)
BACKUP_PASSPHRASE=$(openssl rand -base64 32)

cat > .env <<EOF
# AgentCMS Production Configuration
# Generated by bootstrap_vm.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# --- Runtime ---
APP_ENV=production
APP_NAME=AgentCMS
APP_VERSION=0.3.1
LOG_LEVEL=INFO
LOG_FORMAT=json
DOCS_ENABLED=true
HOST=0.0.0.0
PORT=8000
CORS_ORIGINS=

# --- Security ---
SECRET_KEY=$SECRET_KEY
DEBUG=false

# --- Database ---
DATABASE_URL=postgresql+psycopg://agentcms:$POSTGRES_PASSWORD@db:5432/agentcms
POSTGRES_USER=agentcms
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=agentcms
DB_POOL_SIZE=5
DB_POOL_TIMEOUT=5
DB_ECHO=false

# --- Content Defaults ---
DEFAULT_SITE_SLUG=blog
DEFAULT_PUBLISH_MODE=auto
IDEMPOTENCY_RETENTION_HOURS=24

# --- Capability Links ---
CAPABILITY_DEFAULT_TTL_MINUTES=60
CAPABILITY_MAX_TTL_DAYS=30
CAPABILITY_RATE_LIMIT_PER_LINK=30
CAPABILITY_RATE_LIMIT_WINDOW_SECONDS=60
CAPABILITY_MAX_LIVE_LINKS_PER_SITE=100

# --- Observability ---
METRICS_TOKEN=$METRICS_TOKEN
OTLP_ENDPOINT=
OTEL_SERVICE_NAME=agentcms
TRACE_SAMPLE_RATIO=0.1
GIT_SHA=
BUILD_TIME=

# --- Backups ---
BACKUP_STORE_URL=file:///opt/agentcms/backups
BACKUP_DIR=/opt/agentcms/backups
BACKUP_PASSPHRASE=$BACKUP_PASSPHRASE
BACKUP_RETENTION_DAILY=30
BACKUP_RETENTION_MONTHLY=12
BACKUP_SOURCE_URL=

# --- Reverse Proxy (Caddy) ---
DOMAIN=$DOMAIN
CADDY_EMAIL=$EMAIL

# --- Embed Configuration ---
EMBED_ORIGINS=
EMBED_TOKEN_SCOPE=posts:read

# --- Version Pinning ---
AGENTCMS_IMAGE_TAG=
EOF

log_info ".env created with generated secrets"

# Fill anything left blank/unsafe (AGENTCMS_IMAGE_TAG is required in production).
./scripts/selfhost.sh --setup-only --env-file .env

# 4. Create backup directory
mkdir -p /opt/agentcms/backups
chown -R 10001:10001 /opt/agentcms/backups 2>/dev/null || true

# 5. Deploy
log_info "Starting AgentCMS stack..."
docker compose --env-file .env -f deploy/compose/docker-compose.prod.yml up -d --build

# 6. Wait for health
log_info "Waiting for services to become healthy..."
sleep 10

for i in {1..30}; do
    if curl -fsS "http://127.0.0.1:8000/healthz" >/dev/null 2>&1; then
        log_info "API is healthy!"
        break
    fi
    if [[ $i -eq 30 ]]; then
        log_error "API did not become healthy in time"
        docker compose --env-file .env -f deploy/compose/docker-compose.prod.yml logs --tail=50
        exit 1
    fi
    sleep 2
done

# 7. Verify HTTPS (if domain is not localhost)
if [[ "$DOMAIN" != "localhost" ]]; then
    log_info "Waiting for Caddy to provision TLS certificate for $DOMAIN..."
    for i in {1..60}; do
        if curl -fsS "https://$DOMAIN/healthz" >/dev/null 2>&1; then
            log_info "HTTPS is working on https://$DOMAIN"
            break
        fi
        if [[ $i -eq 60 ]]; then
            log_warn "HTTPS not ready yet (DNS may still be propagating). Check 'docker compose logs caddy'."
        fi
        sleep 5
    done
else
    log_info "Local mode (self-signed certs): https://localhost/healthz"
fi

# 8. Output summary
log_info "============================================"
log_info "BOOTSTRAP COMPLETE ✓"
log_info "============================================"
log_info "AgentCMS is running at:"
if [[ "$DOMAIN" != "localhost" ]]; then
    log_info "  HTTPS: https://$DOMAIN"
else
    log_info "  HTTPS (self-signed): https://localhost"
fi
log_info "  Health: /healthz"
log_info "  Dashboard: /dashboard"
log_info ""
log_info "Next steps:"
log_info "  1. Open the dashboard and create an admin token"
log_info "  2. Create a site (slug: blog)"
log_info "  3. Create a capability link with 'posts:read' for embedding"
log_info "  4. Add the embed script to your frontend:"
log_info ""
log_info "     <script"
log_info "       src=\"https://$DOMAIN/embed/v1/agentcms.js\""
log_info "       data-site-token=\"cap_blog_xxx...\""
log_info "       data-mount=\"#cms\""
log_info "     ></script>"
log_info "     <div id=\"cms\"></div>"
log_info ""
log_info "Configuration: $INSTALL_DIR/.env"
log_info "Logs: docker compose --env-file .env -f deploy/compose/docker-compose.prod.yml logs -f"
log_info "Update: cd $INSTALL_DIR && git pull && docker compose --env-file .env -f deploy/compose/docker-compose.prod.yml up -d --build"